"""Shared database helpers with SQLite/Postgres groundwork.

The repo still runs on SQLite by default, but these helpers centralize:
- database target resolution
- backend detection
- connection setup
- generic table introspection
- inserts that return a generated id

That keeps the current flow working while making a later Postgres move much
less invasive.
"""

from __future__ import annotations

import os
import sqlite3
from typing import Iterable, Sequence


DEFAULT_SQLITE_DB = "sealed_market.db"

try:  # pragma: no cover - optional dependency
    import psycopg
except Exception:  # pragma: no cover
    psycopg = None

try:  # pragma: no cover - optional dependency
    import psycopg2
except Exception:  # pragma: no cover
    psycopg2 = None


def resolve_database_target(explicit=None, default=DEFAULT_SQLITE_DB):
    for candidate in (
        explicit,
        os.getenv("DATABASE_URL"),
        os.getenv("DB_URL"),
        os.getenv("DB_PATH"),
        default,
    ):
        if candidate:
            return candidate
    return default


def is_postgres_target(target):
    return bool(target) and str(target).startswith(("postgres://", "postgresql://"))


def is_sqlite_target(target):
    return not is_postgres_target(target)


def get_dialect(conn_or_target):
    if isinstance(conn_or_target, str):
        return "postgres" if is_postgres_target(conn_or_target) else "sqlite"

    module = conn_or_target.__class__.__module__
    if module.startswith("psycopg") or module.startswith("psycopg2"):
        return "postgres"
    return "sqlite"


def connect_database(target=None):
    target = resolve_database_target(target)
    if is_postgres_target(target):
        if psycopg is not None:
            return psycopg.connect(target)
        if psycopg2 is not None:
            return psycopg2.connect(target)
        raise RuntimeError("Postgres target provided but psycopg/psycopg2 is not installed")
    return sqlite3.connect(target)


def configure_connection(conn):
    if get_dialect(conn) == "sqlite":
        cursor = conn.cursor()
        cursor.execute("PRAGMA foreign_keys = ON")
        cursor.execute("PRAGMA journal_mode = WAL")
        cursor.execute("PRAGMA synchronous = NORMAL")
        conn.commit()
        return

    # Keep Postgres setup intentionally light. Session settings can be expanded
    # later once a full migration is in place.
    try:  # pragma: no cover - depends on live Postgres backend
        cursor = conn.cursor()
        cursor.execute("SET TIME ZONE 'UTC'")
        conn.commit()
    except Exception:
        pass


def table_exists(conn, table_name):
    c = conn.cursor()
    if get_dialect(conn) == "sqlite":
        c.execute(
            """
            SELECT 1
            FROM sqlite_master
            WHERE type = 'table' AND name = ?
            LIMIT 1
            """,
            (table_name,),
        )
    else:
        c.execute(
            """
            SELECT 1
            FROM information_schema.tables
            WHERE table_schema = current_schema()
              AND table_name = %s
            LIMIT 1
            """,
            (table_name,),
        )
    return c.fetchone() is not None


def table_columns(conn, table_name):
    c = conn.cursor()
    if get_dialect(conn) == "sqlite":
        c.execute(f"PRAGMA table_info({table_name})")
        return {row[1] for row in c.fetchall()}

    c.execute(
        """
        SELECT column_name
        FROM information_schema.columns
        WHERE table_schema = current_schema()
          AND table_name = %s
        ORDER BY ordinal_position
        """,
        (table_name,),
    )
    return {row[0] for row in c.fetchall()}


def id_column_sql(dialect, integer_type="INTEGER", autoincrement=True):
    if dialect == "postgres":
        if autoincrement:
            return f"id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
        return f"id {integer_type} PRIMARY KEY"
    if autoincrement:
        return "id INTEGER PRIMARY KEY AUTOINCREMENT"
    return "id INTEGER PRIMARY KEY"


def sql_placeholder_list(conn, count):
    return ", ".join(["%s" if get_dialect(conn) == "postgres" else "?"] * count)


def insert_row_returning_id(conn, table, columns, values):
    c = conn.cursor()
    placeholders = sql_placeholder_list(conn, len(values))
    column_sql = ", ".join(columns)
    sql = f"INSERT INTO {table} ({column_sql}) VALUES ({placeholders})"
    if get_dialect(conn) == "postgres":
        sql += " RETURNING id"
        c.execute(sql, values)
        row = c.fetchone()
        if not row:
            raise RuntimeError(f"Failed to return inserted id for {table}")
        return row[0]

    c.execute(sql, values)
    return c.lastrowid

